name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Push a file to another repository
      uses: nandanidabhi/parallel_workspace@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'swagger.json'
        destination_repo: 'nandanidabhi/Project'
        destination_folder: ''
        user_email: 'nandanidabhi2@gmail.com'
        user_password: 'Twins@123'
        user_name: 'nandanidabhi'
        commit_message: 'A custom message for the commit'
